# frozen_string_literal: true

require_relative "fake_aiweb_cli_setup_tooling"
require_relative "fake_aiweb_cli_engine_tooling"
require_relative "fake_aiweb_cli_verify_loop_tooling"

module FakeAiwebCliRuntimeTooling
end
