# frozen_string_literal: true

module Aiweb
  class DesignCandidateGenerator
    CANDIDATE_IDS = %w[candidate-01 candidate-02 candidate-03].freeze

    Candidate = Struct.new(
      :id,
      :theme,
      :strategy_id,
      :mood,
      :layout,
      :first_view,
      :proof_pattern,
      :cta_flow,
      :mobile_behavior,
      :strengths,
      :tradeoffs,
      :risks,
      :score,
      :rubric_scores,
      :html,
      keyword_init: true
    )

    def initialize(root:, aiweb_dir:, intent:, design_markdown:, design_brief:)
      @root = root
      @aiweb_dir = aiweb_dir
      @intent = intent || {}
      @design_markdown = design_markdown.to_s
      @design_brief = design_brief.to_s
    end

    def candidates
      @candidates ||= CANDIDATE_IDS.each_with_index.map do |id, index|
        spec = route_specs.fetch(index)
        Candidate.new(
          id: id,
          theme: spec.fetch(:theme),
          strategy_id: strategy_id_for(spec.fetch(:theme)),
          mood: spec.fetch(:mood),
          layout: spec.fetch(:layout),
          first_view: first_view_for(spec),
          proof_pattern: proof_pattern_for(spec.fetch(:theme)),
          cta_flow: cta_flow_for(spec.fetch(:theme)),
          mobile_behavior: mobile_behavior_for(spec.fetch(:theme)),
          strengths: spec.fetch(:strengths),
          tradeoffs: spec.fetch(:tradeoffs),
          risks: risks_for(spec),
          score: candidate_score_for(spec.fetch(:theme)),
          rubric_scores: candidate_rubric_scores(spec.fetch(:theme)),
          html: html_for(id, spec)
        )
      end
    end

    def comparison_markdown
      rows = candidates.map do |candidate|
        "| #{candidate.id} | #{candidate.strategy_id} | #{candidate.score} | #{candidate.first_view} | #{candidate.proof_pattern} | #{candidate.cta_flow} | #{candidate.mobile_behavior} | #{candidate.risks.join('; ')} |"
      end.join("\n")
      note_rows = candidates.map do |candidate|
        "| #{candidate.id} | #{candidate.mood} | #{candidate.layout} | #{candidate.strengths.join('; ')} | #{candidate.tradeoffs.join('; ')} |"
      end.join("\n")
      reference_basis = reference_basis_markdown

      <<~MD
        # Design Candidate Comparison

        Source of truth: `.ai-web/DESIGN.md`
        Generated candidates: #{CANDIDATE_IDS.length}
        Route: #{market_route}
        Design system ID: #{design_system_id}
        Skill ID: #{skill_id}

        #{reference_basis}

        | Candidate | Strategy | Score | First-view | Proof pattern | CTA flow | Mobile behavior | Risks |
        |---|---|---:|---|---|---|---|---|
        #{rows}

        ## Strategy Coverage
        - editorial-premium: #{candidate_for_strategy("editorial-premium")&.id || "missing"}
        - conversion-focused: #{candidate_for_strategy("conversion-focused")&.id || "missing"}
        - trust-minimal: #{candidate_for_strategy("trust-minimal")&.id || "missing"}

        ## Candidate Notes
        | Candidate | Mood | Layout | Strengths | Tradeoffs |
        |---|---|---|---|---|
        #{note_rows}

        ## Review Guidance
        - Choose the candidate that best satisfies `.ai-web/DESIGN.md`, `.ai-web/design-brief.md`, and `.ai-web/first-view-contract.md`.
        - When `.ai-web/design-reference-brief.md` is present, prefer candidates that translate reference patterns into original hierarchy and component decisions.
        - Do not treat placeholder proof, placeholder logos, draft prices, or testimonial slots as real claims.
        - Do not copy exact reference screenshots, layouts, copy, prices, trademarks, or brand-specific claims.
        - Selection writes `.ai-web/design-candidates/selected.md`; `.ai-web/DESIGN.md` remains the source of truth unless explicitly regenerated by the existing design-system command.
      MD
    end

    private

    attr_reader :intent, :design_markdown, :design_brief

    def candidate_for_strategy(strategy_id)
      candidates.find { |candidate| candidate.strategy_id == strategy_id }
    end

    def strategy_id_for(theme)
      case theme
      when "editorial-luxury" then "editorial-premium"
      when "trust-service" then "trust-minimal"
      else "conversion-focused"
      end
    end

    def candidate_score_for(theme)
      case strategy_id_for(theme)
      when "editorial-premium" then 84
      when "conversion-focused" then 86
      else 85
      end
    end

    def candidate_rubric_scores(theme)
      case strategy_id_for(theme)
      when "editorial-premium"
        { "first_impression" => 90, "hierarchy" => 84, "originality" => 88, "conversion_clarity" => 78, "mobile_polish" => 82 }
      when "conversion-focused"
        { "first_impression" => 84, "hierarchy" => 88, "originality" => 78, "conversion_clarity" => 91, "mobile_polish" => 86 }
      else
        { "first_impression" => 82, "hierarchy" => 86, "originality" => 80, "conversion_clarity" => 84, "mobile_polish" => 88 }
      end
    end

    def first_view_for(spec)
      "#{spec.fetch(:mood)}; #{spec.fetch(:layout)}"
    end

    def proof_pattern_for(theme)
      case strategy_id_for(theme)
      when "editorial-premium" then "source-backed narrative details and restrained proof slots"
      when "conversion-focused" then "benefit proof panel, comparison grid, and claim-safe CTA support"
      else "calm reassurance row, process evidence, and no unsupported proof"
      end
    end

    def cta_flow_for(theme)
      case strategy_id_for(theme)
      when "editorial-premium" then "quiet primary CTA with secondary review path"
      when "conversion-focused" then "dominant primary CTA with repeated mobile-safe action"
      else "clear contact or next-step CTA with reassurance before commitment"
      end
    end

    def mobile_behavior_for(theme)
      case strategy_id_for(theme)
      when "editorial-premium" then "stacked editorial rhythm with preserved first-view hierarchy"
      when "conversion-focused" then "sticky or repeated action, compact proof, and short scan path"
      else "single-column trust flow with visible contact/action affordance"
      end
    end

    def risks_for(spec)
      spec.fetch(:tradeoffs).map { |item| item.to_s.sub(/\Aneeds? /i, "needs ") }
    end

    def route_specs
      case market_route
      when "saas"
        [
          {
            theme: "conversion-product",
            mood: "Product-led, precise, and action-oriented",
            layout: "Split hero with product workflow panel, capability cards, and CTA band",
            strengths: ["fast value comprehension", "strong primary action hierarchy", "clear component extraction"],
            tradeoffs: ["less atmospheric brand depth", "requires disciplined product copy"]
          },
          {
            theme: "trust-service",
            mood: "Calm operational trust with safety-forward proof slots",
            layout: "Centered hero, compliance-safe reassurance row, process ladder, FAQ preview",
            strengths: ["low claim risk", "good for regulated or B2B buyers", "accessible hierarchy"],
            tradeoffs: ["can feel conservative", "needs real proof before launch"]
          },
          {
            theme: "editorial-luxury",
            mood: "Editorial software narrative with premium restraint",
            layout: "Magazine-style lead, large whitespace, annotated product moments, quiet CTA",
            strengths: ["distinctive brand feel", "less dashboard cliché", "strong typography direction"],
            tradeoffs: ["conversion cues are subtler", "more care needed on responsive spacing"]
          }
        ]
      when "ecommerce"
        [
          {
            theme: "commerce-mobile",
            mood: "Mobile-first, shoppable, and reassuring",
            layout: "Sticky commerce header, collection hero, product cards, safe offer/help modules",
            strengths: ["tap-friendly browsing", "clear product decision flow", "strong mobile contract"],
            tradeoffs: ["higher density", "needs real product data to replace placeholders"]
          },
          {
            theme: "editorial-luxury",
            mood: "Curated collection story with premium pacing",
            layout: "Editorial hero, featured collection strip, material/detail blocks, measured CTA",
            strengths: ["brand differentiation", "good for premium assortment", "strong imagery direction"],
            tradeoffs: ["slower direct shopping", "requires high-quality source imagery"]
          },
          {
            theme: "conversion-product",
            mood: "Direct product value with clear purchase-path reassurance",
            layout: "Value hero, product proof placeholders, comparison grid, shipping/help band",
            strengths: ["strong conversion clarity", "safe provenance reminders", "straightforward implementation"],
            tradeoffs: ["less bespoke atmosphere", "can become generic if copy is thin"]
          }
        ]
      when "service"
        [
          {
            theme: "trust-service",
            mood: "Warm local trust and appointment readiness",
            layout: "Service hero with contact panel, location/hours module, process cards, safe proof slots",
            strengths: ["clear booking/contact path", "trustworthy without fake claims", "excellent local-service fit"],
            tradeoffs: ["conservative visual energy", "needs owner-supplied local details"]
          },
          {
            theme: "editorial-luxury",
            mood: "Refined neighborhood editorial with calm confidence",
            layout: "Large typographic hero, story/detail sections, service menu, quiet contact CTA",
            strengths: ["distinctive premium feel", "good for high-touch services", "strong whitespace discipline"],
            tradeoffs: ["booking action is less forceful", "imagery must be carefully sourced"]
          },
          {
            theme: "conversion-product",
            mood: "Practical service conversion with immediate next steps",
            layout: "Problem-fit hero, service cards, eligibility/visit checklist, sticky CTA footer",
            strengths: ["high action clarity", "mobile-friendly conversion path", "easy QA mapping"],
            tradeoffs: ["less editorial softness", "can feel utilitarian"]
          }
        ]
      else
        [
          {
            theme: "editorial-luxury",
            mood: "Premium editorial restraint with crafted hierarchy",
            layout: "Asymmetric hero, image/detail rail, modular narrative sections, quiet CTA",
            strengths: ["strong brand memorability", "clear token direction", "avoids template sameness"],
            tradeoffs: ["requires careful content editing", "conversion path is measured"]
          },
          {
            theme: "trust-service",
            mood: "Credible and reassuring with service-grade clarity",
            layout: "Centered promise, trust-safe proof placeholders, process cards, contact/help strip",
            strengths: ["low fake-proof risk", "accessible content hierarchy", "safe default for broad briefs"],
            tradeoffs: ["less dramatic visual identity", "needs source-backed proof later"]
          },
          {
            theme: "conversion-product",
            mood: "Focused conversion/product clarity",
            layout: "Direct hero, action panel, benefit grid, implementation-ready component sections",
            strengths: ["strong first-view action", "simple implementation", "clear section IDs"],
            tradeoffs: ["less luxurious", "may need brand polish after selection"]
          }
        ]
      end
    end

    def html_for(id, spec)
      color = theme_color(spec.fetch(:theme))
      obligations = first_view_obligations.map do |item|
        "<li><span>Required</span>#{escape_html(item.to_s.tr('_', ' '))}</li>"
      end.join("\n            ")
      obligations = "<li><span>Required</span>Follow approved first-view contract</li>" if obligations.empty?

      <<~HTML
        <!doctype html>
        <html lang="en" data-aiweb-route="#{escape_attr(market_route)}" data-aiweb-design-system="#{escape_attr(design_system_id)}" data-aiweb-skill="#{escape_attr(skill_id)}">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>#{id} — #{escape_html(spec.fetch(:theme))} design candidate</title>
          <style>
            :root { color-scheme: light; --ink: #171514; --muted: #6d665f; --paper: #{color.fetch(:paper)}; --panel: #{color.fetch(:panel)}; --accent: #{color.fetch(:accent)}; --line: #{color.fetch(:line)}; }
            * { box-sizing: border-box; }
            body { margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: var(--paper); color: var(--ink); }
            .shell { min-height: 100vh; padding: 24px; }
            .candidate { max-width: 1180px; margin: 0 auto; border: 1px solid var(--line); background: rgba(255,255,255,.72); box-shadow: 0 24px 80px rgba(23,21,20,.08); }
            header { display: flex; justify-content: space-between; gap: 16px; align-items: center; padding: 18px 22px; border-bottom: 1px solid var(--line); }
            .brand { font-weight: 780; letter-spacing: -.03em; }
            .route { color: var(--muted); font-size: 13px; }
            .hero { display: grid; grid-template-columns: #{hero_columns(spec.fetch(:theme))}; min-height: 540px; }
            .hero-copy { padding: clamp(28px, 6vw, 76px); display: flex; flex-direction: column; justify-content: center; gap: 22px; }
            .eyebrow { color: var(--accent); text-transform: uppercase; letter-spacing: .14em; font-size: 12px; font-weight: 760; }
            h1 { margin: 0; font-size: clamp(42px, 7vw, 92px); line-height: .91; letter-spacing: -.075em; max-width: 850px; }
            .summary { max-width: 640px; color: var(--muted); font-size: clamp(17px, 2vw, 21px); line-height: 1.55; }
            .actions { display: flex; gap: 12px; flex-wrap: wrap; }
            .button { border: 1px solid var(--ink); border-radius: 999px; padding: 13px 18px; font-weight: 760; background: var(--ink); color: white; text-decoration: none; }
            .button.secondary { background: transparent; color: var(--ink); }
            .panel { background: var(--panel); border-left: 1px solid var(--line); padding: clamp(22px, 4vw, 44px); display: flex; flex-direction: column; justify-content: center; gap: 18px; }
            .card { border: 1px solid var(--line); border-radius: #{card_radius(spec.fetch(:theme))}; padding: 18px; background: rgba(255,255,255,.62); }
            .card strong { display: block; margin-bottom: 8px; }
            .contract { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; padding: 18px; border-top: 1px solid var(--line); background: rgba(255,255,255,.45); }
            .contract section { min-height: 150px; }
            ul { margin: 0; padding: 0; list-style: none; }
            li { padding: 10px 0; border-bottom: 1px solid var(--line); color: var(--muted); }
            li span { display: block; color: var(--ink); font-size: 11px; text-transform: uppercase; letter-spacing: .12em; font-weight: 760; }
            .mobile-bar { display: none; position: sticky; bottom: 0; border-top: 1px solid var(--line); background: var(--paper); padding: 12px; }
            @media (max-width: 760px) { .shell { padding: 0; } .candidate { border-width: 0; } header { align-items: flex-start; flex-direction: column; } .hero { grid-template-columns: 1fr; min-height: auto; } .panel { border-left: 0; border-top: 1px solid var(--line); } .contract { grid-template-columns: 1fr; } .mobile-bar { display: block; } }
          </style>
        </head>
        <body>
          <!-- aiweb:visual-contract:start #{id} -->
          <main class="shell" data-aiweb-id="candidate.#{id}.preview">
            <article class="candidate" data-aiweb-id="candidate.#{id}.canvas" aria-label="#{escape_attr(id)} design candidate preview">
              <header data-aiweb-id="candidate.#{id}.header">
                <div class="brand">Draft brand system</div>
                <div class="route">Route: #{escape_html(market_route)} · Design system: #{escape_html(design_system_id)} · Skill: #{escape_html(skill_id)}</div>
              </header>
              <section class="hero" data-aiweb-id="candidate.#{id}.first-view">
                <div class="hero-copy" data-aiweb-id="candidate.#{id}.hero-copy">
                  <div class="eyebrow">#{escape_html(spec.fetch(:theme))}</div>
                  <h1>#{escape_html(headline_for(spec.fetch(:theme)))}</h1>
                  <p class="summary">#{escape_html(summary_for(spec.fetch(:theme)))}</p>
                  <nav class="actions" aria-label="Draft primary actions" data-aiweb-id="candidate.#{id}.actions">
                    <a class="button" href="#" data-aiweb-id="candidate.#{id}.primary-cta">Primary action placeholder</a>
                    <a class="button secondary" href="#" data-aiweb-id="candidate.#{id}.secondary-cta">Review source-backed details</a>
                  </nav>
                </div>
                <aside class="panel" data-aiweb-id="candidate.#{id}.route-panel">
                  <div class="card" data-aiweb-id="candidate.#{id}.visual-contract-card">
                    <strong>Visual contract</strong>
                    <p>Generated from `.ai-web/DESIGN.md`; preserve stable `data-aiweb-id` hooks and route IDs during implementation.</p>
                  </div>
                  <div class="card" data-aiweb-id="candidate.#{id}.proof-placeholder">
                    <strong>Proof slot is placeholder-safe</strong>
                    <p>No fake metrics, testimonials, logos, prices, or credentials. Replace only with owner-provided sources.</p>
                  </div>
                  <div class="card" data-aiweb-id="candidate.#{id}.mobile-note">
                    <strong>Mobile behavior</strong>
                    <p>First-view action remains visible; sections stack without horizontal scroll.</p>
                  </div>
                  #{reference_card_html}
                </aside>
              </section>
              <div class="contract" data-aiweb-id="candidate.#{id}.contract-sections">
                <section class="card" data-aiweb-id="candidate.#{id}.first-view-obligations">
                  <strong>First-view obligations</strong>
                  <ul>
                    #{obligations}
                  </ul>
                </section>
                <section class="card" data-aiweb-id="candidate.#{id}.layout-notes">
                  <strong>Layout direction</strong>
                  <p>#{escape_html(spec.fetch(:layout))}</p>
                </section>
                <section class="card" data-aiweb-id="candidate.#{id}.tradeoff-notes">
                  <strong>Review tradeoffs</strong>
                  <p>#{escape_html(spec.fetch(:tradeoffs).join('; '))}</p>
                </section>
              </div>
            </article>
            <div class="mobile-bar" data-aiweb-id="candidate.#{id}.mobile-sticky-action">Mobile sticky action placeholder — source-safe</div>
          </main>
          <!-- aiweb:visual-contract:end #{id} -->
        </body>
        </html>
      HTML
    end

    def headline_for(theme)
      case theme
      when "editorial-luxury" then "A restrained first view with room for the brand to breathe"
      when "trust-service" then "Clear next steps, calm proof, and no unsupported claims"
      when "commerce-mobile" then "A shoppable mobile path with every claim marked draft-safe"
      else "A focused product story that makes the primary action obvious"
      end
    end

    def summary_for(theme)
      base = case theme
             when "editorial-luxury" then "Editorial hierarchy, measured whitespace, and source-safe content slots translate the approved route into an implementation-ready visual direction."
             when "trust-service" then "Trust cues, contact or action clarity, and practical service structure are prioritized without inventing reviews, credentials, or results."
             when "commerce-mobile" then "Product browsing, action placement, and reassurance modules are organized for small screens while keeping all product claims as placeholders."
             else "The candidate emphasizes conversion clarity, reusable components, route-specific constraints, and visual hooks ready for downstream code generation."
             end
      "#{base} Primary interaction: #{primary_interaction}."
    end

    def reference_card_html
      return "" unless reference_brief_present?

      <<~HTML.chomp
        <div class="card" data-aiweb-id="candidate.reference-basis">
          <strong>Reference basis</strong>
          <p>Use `.ai-web/design-reference-brief.md` for pattern grounding only: hierarchy, CTA, layout, visual language, responsive behavior, and trust cues. Do not copy exact reference UI, copy, prices, trademarks, or signed image URLs.</p>
        </div>
      HTML
    end

    def reference_basis_markdown
      return "Reference basis: none recorded; generated from deterministic local design artifacts only." unless reference_brief_present?

      summary = reference_brief_summary
      <<~MD.rstrip
        ## Reference basis
        - Source: `.ai-web/design-reference-brief.md`
        - Use only pattern-level guidance from the reference brief; avoid exact copying, brand imitation, signed image URL dependence, prices, trademarks, or reference-specific copy.
        #{summary.empty? ? "- Summary: reference brief present; review it before selecting a candidate." : "- Summary: #{summary}"}
      MD
    end

    def reference_brief_present?
      reference_brief.length >= 40
    end

    def reference_brief
      @reference_brief ||= begin
        path = File.join(@aiweb_dir, "design-reference-brief.md")
        File.file?(path) ? File.read(path).to_s.strip : ""
      end
    end

    def reference_brief_summary
      reference_brief
        .lines
        .map(&:strip)
        .reject { |line| line.empty? || line.start_with?("#") || line.start_with?("!") }
        .first(2)
        .join(" ")
        .gsub("|", "/")
        .slice(0, 220)
        .to_s
    end

    def first_view_obligations
      Array(intent["must_have_first_view"]).reject { |item| item.to_s.strip.empty? }
    end

    def primary_interaction
      value = intent["primary_interaction"].to_s.strip
      value.empty? ? "approved first-view action" : value
    end

    def market_route
      present(intent["market_archetype"], intent["archetype"] || "fallback")
    end

    def design_system_id
      from_design = design_markdown[/Selected design system ID:\s*([^\n]+)/, 1]
      present(from_design, intent["recommended_design_system"] || "luxury-editorial")
    end

    def skill_id
      from_design = design_markdown[/Selected skill ID:\s*([^\n]+)/, 1]
      present(from_design, intent["recommended_skill"] || "premium-landing-page")
    end

    def present(value, fallback)
      string = value.to_s.strip
      string.empty? ? fallback : string
    end

    def theme_color(theme)
      case theme
      when "trust-service"
        { paper: "#f7f3ec", panel: "#efe5d6", accent: "#6f5b32", line: "#ded2c1" }
      when "conversion-product"
        { paper: "#f6f8fb", panel: "#e7edf7", accent: "#3057d5", line: "#d8e0ee" }
      when "commerce-mobile"
        { paper: "#fbf7f2", panel: "#f3e6da", accent: "#a85e2a", line: "#e5d7ca" }
      else
        { paper: "#f5f1ea", panel: "#e8dfd1", accent: "#8b6c38", line: "#d8cdbc" }
      end
    end

    def hero_columns(theme)
      case theme
      when "editorial-luxury" then "1.25fr .75fr"
      when "commerce-mobile" then ".9fr 1.1fr"
      else "1fr 1fr"
      end
    end

    def card_radius(theme)
      theme == "conversion-product" ? "18px" : "2px"
    end

    def escape_html(value)
      value.to_s.gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;")
    end

    def escape_attr(value)
      escape_html(value).gsub('"', "&quot;")
    end
  end
end
